{{- if .Values.agent.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-aeo-agent-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}