{{- if .Values.agent.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-aeo-agent-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-aeo-agent-services
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-aeo-agent-ctl-log
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 1Gi          
{{- end }}