# Default values for mobius.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  agent: docker.io/library/aeo-agent:nightly
  
agent:
  enabled: true
  name: aeo-agent
    
  additionalVolumes:
  - name: jenkins
    persistentVolumeClaim:
      claimName: jenkins

  additionalVolumeMounts:
  - mountPath: /bitnami/jenkins
    name: jenkins

