# Default values for mobius.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  scheduler: docker.io/library/aeo-scheduler:nightly
  clientmgr: docker.io/library/aeo-clientmgr:nightly
  agent: docker.io/library/aeo-agent:nightly
  database: postgres:12-alpine
  
scheduler:
  enabled: true
  name: aeo-scheduler
  #nodePort: 30789
  database:
    driver: "org.postgresql.Driver"   
    type: "POSTGRESQL"   
    url: "jdbc:postgresql://aeo-postgres:5432/aeo"
    name: "aeo"
    server: "aeo-postgres"
    user: "aeo"
    password: "3Zwzef7ZkyYCmSu5wq6YdPL446Y6Mvt7U8rq4NhLrt7rVX5Q3k6zxpNKHsifmlDFp"

clientmgr:
  name: aeo-clientmgr

agent:
  enabled: true
  name: aeo-agent


ingress:
  enabled: true
  className: "public"
  host: aeo.rocket.dev.com
  tls:
    secretName: "tls-dev"
    # aeo.rocket.dev.com crt, and key certificate files in base64
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXekNDQWtPZ0F3SUJBZ0lVZkZIWWJiWFpOQTZjOVlNbGNBblAzV0dpUlM4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0hURWJNQmtHQTFVRUF3d1NZV1Z2TG5KdlkydGxkQzVrWlhZdVkyOXRNQjRYRFRJeU1EZ3hPREU0TkRBegpOVm9YRFRNeU1EZ3hOVEU0TkRBek5Wb3dIVEViTUJrR0ExVUVBd3dTWVdWdkxuSnZZMnRsZEM1a1pYWXVZMjl0Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBd0cwNzNKYkcra04ra1QwZFp5SGcKUnk3ejlRcU0rVlhsSklHMjFNeitBMDhjRWF4UlJxdU5oWVp5YmJlTm4xaEU4aTREazBiRzJ0enF6Ukl3dWttOAppTWp1b3RFdEFSUk1mYVZPV1hBSC84bHE1TTExMFdlQjRrWXcvb0x0ZVc4M3ZOK29McmdBTnhYQzhNeGphYXlYCk5sRXhteVVvUTNXUnRaSXhXMWxXcUhGdjhWcnNFcjdhenljZkEwZVJPOTNGRHd4Vnhad2JuNCtXVDdXK0EyN1EKNnlrZkFXaU5pZloybzBNcVJjZFhtejdhTlRBeTFuTldGNG54VGpkd0VLYUlXNUVhQndhMHZ1SUJIalZ2emhiKwpwZ1djc3ByRWZjcE9GR1g2d3dYTVZRM1ZOZUhIL0pocVhqVGhLSThHM3Zza2pPblBNK0poMTlGS3oxQjk0emVrCm13SURBUUFCbzRHU01JR1BNQjBHQTFVZERnUVdCQlJQbkNNSi9FYisrdFd6SG1mWWtRYnZUc1l6bURBZkJnTlYKSFNNRUdEQVdnQlJQbkNNSi9FYisrdFd6SG1mWWtRYnZUc1l6bURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwRwpBMVVkRVFRV01CU0NFbUZsYnk1eWIyTnJaWFF1WkdWMkxtTnZiVEFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNECkFRWUlLd1lCQlFVSEF3SXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSnVJc01kTzNmSXQxN09vMy8rMmdvQk4KYWNQQVVvT1psMytQMXJ2VC9xUXZyQSs4S0ZXZzQrTzhlQWRVRy92K2plbGx5bHNtc3A1bldkcUpQc3NuYjJLRgpSK1BTdHg0WWFWY2k1REhIeENxaWEwUmdiV0R3UzgrSVNLbTZUd29SVGVTWDFkSFFWZXpTdHJhWnI4bW82dlltCmQ0N1pLVzZ4TEhBdFhCMTk2b0FIN29yQnMzOGFXK2dQeUZjODhXQ2ZTYkI1NmRVZHgwUFlqcUJIay95cTB6UmUKNUt4RWwzR0tDMStPSDloWWM5ZUszckFzakEzWnBNVjQrQWtlc2xrNnNxT1dGRlFtQjZYOFhZZmdhWDRoQkdaYQptNjZTbWkwUzNCajdyK1dwbjNiMkR0ZUkzQ1BQQjV3Tm5hWUltYkJJcHo0YzJtL3Y4RUpuUkFvUUpoSmE1dnc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRREFiVHZjbHNiNlEzNlIKUFIxbkllQkhMdlAxQ296NVZlVWtnYmJVelA0RFR4d1JyRkZHcTQyRmhuSnR0NDJmV0VUeUxnT1RSc2JhM09yTgpFakM2U2J5SXlPNmkwUzBCRkV4OXBVNVpjQWYveVdya3pYWFJaNEhpUmpEK2d1MTViemU4MzZndXVBQTNGY0x3CnpHTnBySmMyVVRHYkpTaERkWkcxa2pGYldWYW9jVy94V3V3U3Z0clBKeDhEUjVFNzNjVVBERlhGbkJ1Zmo1WlAKdGI0RGJ0RHJLUjhCYUkySjluYWpReXBGeDFlYlB0bzFNRExXYzFZWGlmRk9OM0FRcG9oYmtSb0hCclMrNGdFZQpOVy9PRnY2bUJaeXltc1I5eWs0VVpmckRCY3hWRGRVMTRjZjhtR3BlTk9Fb2p3YmUreVNNNmM4ejRtSFgwVXJQClVIM2pONlNiQWdNQkFBRUNnZ0VBRjFzS3lYN3Bmc1hEYm5oM0FhWU1kVWRmSis1VVp3MEVaM1p4RFFvbWlKdEoKQW1JaWFVdjRQTzB4SlYwQ2pRVW5OU2ZkbWpvY2Q4TVpvck5qQTdGZ2QwL0FHelg5V3VTdVZnL0MzenNvVldVSwptdVBQT1kveEpWZzBxU2VXRUVldUFiZzV6eFhaUE5aZzExNVBjS3VZbk9pazl6bysxVlZIVHIwRVRaeWQxb3JjCkVXYlNmSXN1Z3V6ZG1tL095R21pM3BmYWFwYmlzZTRZNmZGbHE2SzFqQ29pdFJibHdFYVdqSWtEcVBJNmU1bG4KVDZUT0lZS014bldHYU1aUHNZRDFqTmVZZDZMcjZ5YVZGdWpHZDdneWFyMXR2MlNwUllzRDBpRGxxcW5xUGRuVAovVjBXTHFFSisxUXJRZEI0Q0wwUGFjT2REZ1RlT0tIQWNTQWJsMjYzU1FLQmdRREpCdldJYy94MmFGczQ5QXIwCnFjOW0xZThEQlV1V3ZDa0l5a2hRVXFkb1VxVUg0MWw0NU5JbTh3eGtHMUxTTWYvQkV1TlhFNVFDTXpScHg3bEIKYjFRNHpWOE9Kb1g2MngrYUlMNzRENmRyZGd0dVphMFM2UlpXNkJySTAxbno0V3hMaHl5WExnWGt1elduNzdqSQp0SzZETVYwd2w0L1BWcGlEQndBRnlKVmNJd0tCZ1FEMURERVlaWWhRN1dmdjdoTXplRDk0WllrN2tMQ2tBK1ZrCkpnc0NVNjFoK0ZubkIxbXp3S0dmSU5JRXo3ZjZwTFZUVWNRM2JLb09PMEEyWGIzNFQ2YnpUeVRyL2dDT0xzdEwKRGpQSjE4NlBEYzNJNWNDcUR6OHRlaStPY2NUQ0c2d3AwYkF6YUNTSWJMOWl2Um9XN1d3TldueUVqZC8xODB1agpKV0xXdEcxQktRS0JnUUNDNDJ3VTUyZ1c5SVdJeEtVcGZqTVRRdkgzWm9nNzRkRlo3dE04c1VSYzBZcXdZeUFMCmJmbEM4UGM5YXVqM0FTVUQ0amR4cDhhejFBRXBhcWc5YWE1TnViSk5kVm5BNXRGaHVqWjlMendUNU8wMmVTOUMKWTg5dTBIczREUnpCaFNITTMzdHlCNzVBbW9BcUV4U2VZYjVLbjJhTXovSUx6dGRJWU5OcjhKa0hQd0tCZ1FERgp6ZStiaCtuL21ZUDY4eXpnc1VKYXgydDlmNUIyOVFZb1QyVTNuYUFwb3pXKy9mbjAxWndoUFhjS2x6b2x3dXJ6CnROODA5aXhYakpDSzBpVFUya2NqeEZGRGhpZWduamxQL3Nqak42YnZadThrS2dIWnhMRDAzdHFnbTBsK2ZxUDgKcGQwYndnY3JjTTBVd1J6Y1FRNmx3Tk1lbFAraUk2QjhzMk1UZVZWdjhRS0JnUUM3aWRPU0V5YTVUY2I0WU5BSQpJaml6QnR4TnpHWmNkaDgwS3ZvaFNsOU9CbHp5M3NhUmJWOEFsYjh1cmI1SW5FSHc3SWR3Q1d2TmNyR1hxRzNhCkdIeXZRaXc4dW1QN3VPcEswM2RxczIzRnFaQUM4Z3dsclVyamxqZHErM2ZMRmZWT0doS0Y4MTBCL1Q0bW9TQWcKYmJ3aHVIVUpHY1VCWndBRS9kM1lHMFhEbXc9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==



