# Default values for mobius.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  agent: docker.io/library/aeo-agent:4.3.0.22
  
agent:
  enabled: true
  name: aeo-agent
    


