apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: /home/rocket/workspace
    type: DirectoryOrCreate