apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: microk8s-hostpath
  volumeName: pv-jenkins-storage
  resources:
    requests:
      storage: 10Gi