{{- if .Values.agent.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.agent.name }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  {{ .Values.agent.name }} 
  template:
    metadata:
      labels:
        app:  {{ .Values.agent.name }} 
    spec:
      hostname:  {{ .Values.agent.name }} 
      containers:
      - name:  {{ .Values.agent.name }} 
        image: {{ .Values.agent.image }}
        imagePullPolicy: IfNotPresent        
        ports:
          - containerPort: 7913
        volumeMounts:
            - mountPath: /opt/aeo/data
              name: pvc-aeo-agent-config
            - mountPath: /opt/aeo/agent/xagent_1
              name: pvc-aeo-agent-services
            {{- if .Values.agent.additionalVolumeMounts -}} 
            {{- toYaml .Values.agent.additionalVolumeMounts | nindent 12 }} 
            {{- end }}   
      volumes:
        - name: pvc-aeo-agent-config
          persistentVolumeClaim:
            claimName: pvc-aeo-agent-config
        - name: pvc-aeo-agent-services
          persistentVolumeClaim:
            claimName: pvc-aeo-agent-services
        {{- if .Values.agent.additionalVolumes -}}
        {{- toYaml .Values.agent.additionalVolumes | nindent 8 }}
        {{- end }}     
{{- end }}