{{- if .Values.agent.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-aeo-agent-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
{{- end }}