{{- if .Values.ldap.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ldapadmin
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName:  {{ .Values.ldap.className}} 
  rules:
  - host: {{ .Values.ldap.hostname}} 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ldapadmin
            port:
              number: 8080
{{- end }}              