{{- if .Values.ldap.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ldapadmin
  name: ldapadmin
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    app: ldapadmin
{{- end }}
