{{- if .Values.ldap.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ldap-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ldap-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}