version: "3.0"

networks:
  k3d-rocket:
    external: true

volumes:
  gfdata:
  pgadmin:

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:8.1.3
    environment: 
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    ports:
      - 3000:3000
    volumes:
      - gfdata:/etc/grafana/provisioning 
    networks:
      - k3d-rocket 
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin     
    networks:
      - k3d-rocket          
